version: '2'
services:
  app:
    image: node:10.6.0-alpine
    command: node --inspect=0.0.0.0:8080 test
    working_dir: /app
    environment:
      CHUNK_SIZE: 10
    ports:
    - 9229:8080
    volumes:
    - ./src:/app/src:ro
    - ./test:/app/test:ro
